### ISSUE TITLE
Warning. Invalid resolution 0 dpi. Using 70 instead.

### ISSUE THREAD

**Issue by JILeXanDR** [tesseract-ocr/tesseract#1702]
command `tesseract https://image.ibb.co/eibzaT/test.png result`

### Current Behavior:
```
Warning. Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 161
Estimating resolution as 161
```

version
```
tesseract 4.0.0-beta.2-313-g29f2
 leptonica-1.76.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.1.0
 Found AVX
 Found SSE
```

original image https://image.ibb.co/eibzaT/test.png

**Comment by amitdo** [comment]
It means your image does not contain a resolution info in its metadata, so Tesseract warns you about this issue in the image and try to estimate the resolution by itself.

**Comment by JILeXanDR** [comment]
@amitdo In which way?

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/blob/2645f72c4a9fecbb19dfe1dc04a94baf723c61b9/src/ccmain/pagesegmain.cpp#L313

By measuring lines height.

**Comment by christophered** [comment]
@zdenop I think, you can close this topic

**Comment by lloiodice** [comment]
/**
     * Save the buffered image to disk.
     *
     * If a PNG is passed add the dot per meter to the pHYS chunkc of the PNG metadata
     * @See PNG Metadata Format Specification - https://docs.oracle.com/javase/8/docs/api/javax/imageio/metadata/doc-files/png_metadata.html
     *
     * 
     * <!ATTLIST "pHYS" "pixelsPerUnitXAxis" #CDATA #REQUIRED>
     * 
     * <!ATTLIST "pHYS" "pixelsPerUnitYAxis" #CDATA #REQUIRED>
     * 
     * <!ATTLIST "pHYS" "unitSpecifier" ("unknown" | "meter") #REQUIRED>
     * 
     *
     *
     * @param bufferedImage image
     * @param formatName PNG, TIFF, etc..
     * @param localOutputFile local filename whene to save te image
     * @param dpi               dot per inches of the image to save
     * @return true if successful, false otherwise
     * @throws IOException
     */
    boolean saveImage(RenderedImage bufferedImage,
                      String formatName,
                      File localOutputFile,
                      int dpi) throws IOException {
        boolean success;

        if (formatName.equals(BlankPageMapRequest.ImageFormat.PNG.toString()))
        {
            ImageWriter writer = ImageIO.getImageWritersByFormatName("png").next();

            ImageWriteParam writeParam = writer.getDefaultWriteParam();
            ImageTypeSpecifier typeSpecifier = ImageTypeSpecifier.createFromBufferedImageType(BufferedImage.TYPE_INT_RGB);

            IIOMetadata metadata = writer.getDefaultImageMetadata(typeSpecifier, writeParam);

            final String pngMetadataFormatName = "javax_imageio_png_1.0";

            // Convert dpi (dots per inch) to dots per meter
            final double metersToInches = 39.3701;
            int dotsPerMeter = (int) Math.round(dpi * metersToInches);

            IIOMetadataNode pHYs_node = new IIOMetadataNode("pHYs");
            pHYs_node.setAttribute("pixelsPerUnitXAxis", Integer.toString(dotsPerMeter));
            pHYs_node.setAttribute("pixelsPerUnitYAxis", Integer.toString(dotsPerMeter));
            pHYs_node.setAttribute("unitSpecifier", "meter");

            IIOMetadataNode root = new IIOMetadataNode(pngMetadataFormatName);
            root.appendChild(pHYs_node);

            metadata.mergeTree(pngMetadataFormatName, root);

            writer.setOutput(ImageIO.createImageOutputStream(localOutputFile));
            writer.write(metadata, new IIOImage(bufferedImage, null, metadata), writeParam);
            writer.dispose();

            success = true;
        }
        else
        {
            success = ImageIO.write(bufferedImage, formatName, localOutputFile);
        }

        return success;
    }

**Comment by lloiodice** [comment]
Tesseract uses Leptonica which uses libpng to read the input image source resolution.
If the input png does not have the correct metadata info, it will generate the warning referred in
this issue. I also seen this to cause tesseract to return slightly different text results for certain images.
The code above adds metadata to the PNG

**Comment by lloiodice** [comment]
To test if an image has the correct header you can use 
magick identify -verbose filename or equivalent tools

and make sure these 2 values are set
Resolution: 118.11x118.11
Units: PixelsPerCentimeter
Above is for a 300 dpi PNG

**Comment by 15013605249** [comment]
@lloiodice The version I am using is 3.05.02 and I can't find the function you said.

**Comment by stweil** [comment]
> tesseract https://image.ibb.co/eibzaT/test.png result

How did you manage that Tesseract could read the input image from a URL?

**Comment by stweil** [comment]
There is an undocumented command line option. Try using `--dpi 300` (or the correct value for your image).

**Comment by zdenop** [comment]
@bhasinnaik : your input image has no information about dpi. If you want to avoid warning, you should fix it.

**Comment by maky-hnou** [comment]
@zdenop , any idea how to fix the photo's DPI when it is 0? 
I tried using different methods (pyexiv2, imagemagick,..) but I still get the same error when I use tesseract...

**Comment by zdenop** [comment]
What did you try with imagemagick? Show your command ;-)

**Comment by maky-hnou** [comment]
`mogrify -set density 300 image.jpg` I found this on a post in Stackoverflow.

**Comment by zdenop** [comment]
Just very easy and short internet search suggest this modification:
`mogrify -set units PixelsPerInch -density 300 image.jpg`

**Comment by maky-hnou** [comment]
Thank you. I already tried that :-D , but still get the same tesseract error. Probably it is because of my image.  
I'll try to find a workaround.  
Thank you again :-)

**Comment by zdenop** [comment]
I tried it and it works for my image.jpg. If you are using tesseract >=4 you can use --dpi option of tesseract executable.

**Comment by jbreiden** [comment]
Try 300x300 with the mogrify command.

**Comment by lloiodice** [comment]
FYI 

In my test of tesseract 4.1 (trying to upgrade from 4.0) .. I get this warning often and 
using 70 dpi instead of the correct dpi affects the efficacy of results especially when 
running script detection. 

In 4.0 setting the metadata in the PNG as described in my post above allowed the correct 
resolution to be used by tesseract. That does not work anymore so something has changed 
in 4.1 (maybe in the dependencies ... libpng? ... not sure).

If anybody knows what PNG metadata fields are necessary to avoid the warning please
let me know ... using the tesseract dpi setting is a complication that would be good to avoid
when processing arbitrary images.

**Comment by zdenop** [comment]
so you have png that does not produce dpi warning with tesseact 4.0, but it produces warning in 4.1?

**Comment by lloiodice** [comment]
It appears to be a problem with script detection

tesseract dpi_issue.png out --psm 0
Tesseract Open Source OCR Engine v4.1.0 with Leptonica
Warning. Invalid resolution 0 dpi. Using 70 instead.

File: 
https://www.dropbox.com/s/y7yb49ew04kj72q/dpi_issue.png?dl=0

When using 300 dpi or with 4.0 I get detected script Han. In 4.1 I get Latin.

**Comment by zdenop** [comment]
interesting: I see file has dpi. Even when I specify dpi for tesseract, I see warning message: 
```
tesseract dpi_issue.png - --dpi 300 --psm 0
Warning. Invalid resolution 0 dpi. Using 70 instead.
Page number: 0
Orientation in degrees: 0
Rotate: 0
Orientation confidence: 7.89
Script: Latin
Script confidence: 0.09
```

**Comment by stweil** [comment]
That's a bug in Tesseract. Tesseract internally creates a new image, but does not copy the resolution from the original image. Fixed now in commit a209a6b4b503c6ada4ce6eb257fde2b76c47f771.

**Comment by zdenop** [comment]
@stweil : Thanks for looking into this. Funny that problem was with `psm 0` only. Others psm works as expected.

**Comment by OmarJabri7** [comment]
I am using pytesseract and there are some images that work with the image_to_osd, but other images do not and the program gives me the following error:
"raise TesseractError(proc.returncode, get_errors(error_string))
pytesseract.pytesseract.TesseractError: (1, 'Tesseract Open Source OCR Engine v4.1.0-bibtag19 with Leptonica Warning. Invalid resolution 0 dpi. Using 70 instead. Too few characters. Skipping this page Error during processing.')"
I am using Python 3.7 anaconda distribution and tesseract >=4.0.0 with pytesseract as a tool.
Please help.

**Comment by stweil** [comment]
Please use the user forum for questions.

**Comment by Prasantkumar987** [comment]
After having an image of 300dpi , then also same error is coming mention below


TesseractError: (3221225501, "read_params_file: Can't open txt Tesseract Open Source OCR Engine v4.1.1 with Leptonica Warning: Invalid resolution 0 dpi. Using 70 instead. Estimating resolution as 711")

**Comment by anilbb23** [comment]
> I am using pytesseract and there are some images that work with the image_to_osd, but other images do not and the program gives me the following error:
> "raise TesseractError(proc.returncode, get_errors(error_string))
> pytesseract.pytesseract.TesseractError: (1, 'Tesseract Open Source OCR Engine v4.1.0-bibtag19 with Leptonica Warning. Invalid resolution 0 dpi. Using 70 instead. Too few characters. Skipping this page Error during processing.')"
> I am using Python 3.7 anaconda distribution and tesseract >=4.0.0 with pytesseract as a tool.
> Please help.

Hi, 
I am getting the same error. How did you resolve it? Please share the solution / sample code.

I am rotating the image with OpenCV and then passing it to  pytesseract.image_to_osd()
TesseractError: (1, 'Tesseract Open Source OCR Engine v5.0.0-alpha.20201127 with Leptonica Warning: Invalid resolution 0 dpi. Using 70 instead. Estimating resolution as 179 Warning. Invalid resolution 0 dpi. Using 70 instead. Too few characters. Skipping this page Error during processing.')

**Comment by esraa-abdelmaksoud** [comment]
I've been using Tesseract for a while and got the same error. I just want to confirm that it is never about the meta data. I got the error while using image_to_osd for photos captured using the same device and this happened to only one of 50 images. I've checked the image details and the dpi already exists. I think it will be something related to the number of characters in the image.

**Comment by esraa-abdelmaksoud** [comment]
I've been using Tesseract for a while and got the same error. I just want to confirm that it is never about the metadata. I got the error while using image_to_osd for photos captured using the same device and this happened to only one of 50 images. I've checked the image details and the dpi already exists. I think it will be something related to the number of characters in the image.

**Comment by esraa-abdelmaksoud** [comment]
I've been using Tesseract for a while and got the same error. I just want to confirm that it is never about the metadata. I got the error while using image_to_osd for photos captured using the same device and this happened to only 3 of 50 images. I've checked the image details and the dpi already exists.

I've been trying to see if the error disappears when I crop the background around the objects in the image, and I saw that the error disappeared for 2 of them, not all of them. I still don't really know the reason, but if it was the metadata, the third one would have worked.

However, I believe that it has something related to the number of characters. The images that resulted in the error that disappeared after cropping were somewhat rotated. The text angle was around 30-40. When it comes to the image that gave error in both cases, it already has a low number of characters. This is why it would be interesting if more people try this so we can figure out if it's really the reason.

**Comment by amitdo** [comment]
Run this command on the original image:
`identify -verbose imagename.jpg`

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects (I assume you use pytesseract based on image_to_osd). Also provide information about tesseract and leptonica version. 
Provide test case to reproduce problem with resent version of tesseract executable - otherwise you are alone with your thoughts and believes.

**Comment by dzg** [comment]
Is there any way to set a default resolution in the event of `Invalid resolution` ? I would like to force `--dpi 72` but only when no DPI detected.

**Comment by stweil** [comment]
That is not directly supported by Tesseract, but could be implemented by a wrapper script.

The current Tesseract release 5.0.0 tries to guess the correct resolution if there is no explicit information from the image file.

**Comment by dzg** [comment]
> That is not directly supported by Tesseract, but could be implemented by a wrapper script.
> 
> The current Tesseract release 5.0.0 tries to guess the correct resolution if there is no explicit information from the image file.

Most of the images I need to process are macOS screenshots – which are all PNG @ 144 DPI – and none of which tesseract recgonizes as having a DPI. Bummer. (Furthermore, to process well I have to set `--dpi 72`)

**Comment by stweil** [comment]
I tested some macOS screenshots, and Tesseract 5.0.0 worked well without the need to give a resolution. But you are free to add `--dpi 72` if that helps for your screenshots.

**Comment by Laxmipriya71** [comment]
By changing the tess4j Version to '5.7.0' and adding the dependency  "implementation group: 'com.asprise.ocr', name: 'java-ocr-api', version: '15.3.0.3'" works for me.
