### ISSUE TITLE
tesseract with costura.fody

### ISSUE THREAD

**Issue by HeroinGyrl** [tesseract-ocr/tesseract#2945]
I cant use tesseract when [Costura.Fody](https://github.com/Fody/Costura) installed.

getting exception
> ArgumentException: The path is in an invalid format

I know that I can uninstall Costura.Fody then it will work.
I want that the tessdata is inside the .dll file.

**Comment by zdenop** [comment]
Tesseract is standard C++ project and there is nothing special regarding paths format.
If you think we break some standard please show where and what should be fixed.

**Comment by HeroinGyrl** [comment]
found this. https://github.com/charlesw/tesseract/issues/485
seems to be incompatibility.

**Comment by BennoArnautovic** [comment]
This is still an issue, is there any fix for this? when using 

`<Costura>
    <ExcludeAssemblies>
        Tesseract
    </ExcludeAssemblies>
</Costura>`

Library is missing on build (which is obvious I guess?), what can be done here?
