### ISSUE TITLE
Floating point error (div by zero) in v5.0.0-alpha-20201231-241-g838a7

### ISSUE THREAD

**Issue by oberw** [tesseract-ocr/tesseract#3314]
### Environment
v5.0.0-alpha-20201231-241-g838a7
lNAME="openSUSE Tumbleweed"
# VERSION="20210223"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20210223"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20210223"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo"

* **Tesseract Version**: 
* **Commit Number**: 
* **Platform**: 

### Current Behavior:
tesseract bombs with signal 8 on dumas_monte_christo/out/Le_comte_de_Monte_Christo_031.tif (attached)
### Expected Behavior:
ocr single page that ocr-ed without error the day before 
tesseract -l fra ./dumas_monte_christo/out/Le_comte_de_Monte_Christo_031.tif xx pdf
Tesseract Open Source OCR Engine v5.0.0-alpha-20201231-241-g838a7 with Leptonica
Page 1
Gleitkomma-Ausnahme (Speicherabzug geschrieben)
(german for core dumped)....
[page31.zip](https://github.com/tesseract-ocr/tesseract/files/6057420/page31.zip)
The tif file causing the coredump  is included in the zip file.

### Suggested Fix:
no suggestion, unfortunately.

**Comment by stweil** [comment]
Thank you for your report. That floating point exception was enabled by code which I added recently to detect errors like this division by zero. I fixed the problem now in commit 339c01894e648e4ede60b37bae1f44866763c88c.

**Comment by Shreeshrii** [comment]
@stweil Please also check Actions CI. Many runs are failing. eg:

```
/home/runner/work/_temp/2ffe6c26-9279-481f-879a-8408f424bf1d.sh: line 1:  8396 Floating point exception(core dumped) build/inst/bin/tesseract 
```

**Comment by stweil** [comment]
Did those tests run before this issue was fixed? I tried some manually, and those worked fine.

**Comment by Shreeshrii** [comment]
cmake
autotools
unittest
vcpkg

The above run every night. Under each you will see a matrix of combinations
that is run. Certain combinations are failing for last 2 days.

You can choose the workflow name from the list on left to see the previous
invocations.

**Comment by Shreeshrii** [comment]
In last nights run, `unittest` was ok but still have some failing runs for `cmake` and `autotools`.  Comparing below clang++-8 on ubntu18.04.

ubuntu-18.04-clang-8-unittest
```
Run ./configure '--disable-shared' \
  ./configure '--disable-shared' \
       'CXX=clang++-8' \
       'CXXFLAGS=-g -O2 -fsanitize=address,undefined'
```

ubuntu-18.04-clang-8-cmake
```
  cmake \
    -S . \
    -B build \
    -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DOPENMP_BUILD=OFF \
    -DCMAKE_CXX_COMPILER=clang++-8 \
    -DCMAKE_INSTALL_PREFIX:PATH=inst
```

linux (ubuntu-18.04-clang-8-autotools, ubuntu-18.04, clang++-8)
```
Run ./configure '--disable-shared' '--disable-openmp' '--disable-doc' 'CXX=clang++-8' 'CXXFLAGS=-g -O2'
  ./configure '--disable-shared' '--disable-openmp' '--disable-doc' 'CXX=clang++-8' 'CXXFLAGS=-g -O2'
```

The difference I notice is that the two cases where running tesseract on the image fails have been built without OPENMP.

**Comment by Shreeshrii** [comment]
My earlier conjecture about `openmp` was incorrect. Some testing shows that the Floating point exception while recognizing phototest.tif goes away if configured the same as the `unittest` run i.e. by adding the following to configure

```
-fsanitize=address,undefined
```

This is the result of a recent change. Used to work earlier. Error is seen while recognizing the image from CLI. API seems to work.

[FAILS](https://github.com/Shreeshrii/tesseract/runs/2022546994?check_suite_focus=true)
```
./configure '--disable-shared' '--disable-openmp' '--disable-doc' 'CXX=clang++-8' 'CXXFLAGS=-g -O2'
```
```
Run time -p tesseract test/testing/phototest.tif - --oem 0  --tessdata-dir ../tessdata
Page 1
/home/runner/work/_temp/8ef5b4b2-999b-4004-bd3a-f2dd132b0830.sh: line 1: 19099 Floating point exception(core dumped) tesseract test/testing/phototest.tif - --oem 0 --tessdata-dir ../tessdata
real 2.03
user 0.16
sys 0.06
```

[WORKS](https://github.com/Shreeshrii/tesseract/runs/2022636223?check_suite_focus=true)
```
Run ./configure '--disable-shared' '--disable-openmp' '--disable-doc' 'CXX=clang++-8' 'CXXFLAGS=-g -O2 -fsanitize=address,undefined'
```
```
Run time -p tesseract test/testing/phototest.tif - --oem 0  --tessdata-dir ../tessdata
Page 1
This is a lot of 12 point text to test the
ocr code and see if it works on all types
of file format.
```

**Comment by stweil** [comment]
I now could reproduce the FAIL with clang-11. The problem disappears when I compile with `-O0` or `-O1`. When I add `printf` statements to debug it, it raises `SIGFPE` in other parts of the code.

I currently think that perhaps clang optimizes FP operations in a way which causes FP exceptions. This seems to be related to SIMD instructions. Example: if two float divisions must be calculated, it uses an operation with two vectors of 4 float values. While the first 2 components give the desired results, the last 2 components are 0 and result in `0 / 0`.

Maybe we should simply not enable FP exceptions clang.

**Comment by Shreeshrii** [comment]
@stweil Thanks, Actions CI is passing for cmake and autottols also.

@oberw Please confirm that you are not getting the error after latest commit from @stweil so that issue can be closed.

**Comment by oberw** [comment]
@Shreeshrii I just pulled: latest commit ID 576c064b44c41c21477eded1dd58ca31d82e3430 (Tesseract Open Source OCR Engine v5.0.0-alpha-20201231-251-g576c0) now processes my 600+page document (French original of the Count of Monte Christo) without error.
