### ISSUE TITLE
PKG_CHECK_MODULES on Ubuntu 14.04.5

### ISSUE THREAD

**Issue by billydekid** [tesseract-ocr/tesseract#405]
Hi, 

I'm on compiling on Ubuntu 14.04.5 at ./configure stage and got error below.
I don't need to install training tools.

```
# ./configure
<skip>
configure: WARNING: Training tools WILL NOT be built because of missing icu library.
configure: WARNING: Try to install libicu-devel package.
./configure: line 17228: syntax error near unexpected token `pango,'
./configure: line 17228: `PKG_CHECK_MODULES(pango, pango, have_pango=true, have_pango=false)'
```

Here's the autoconf version
```
# autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
```
How can to fix it?

Thanks,

**Comment by zdenop** [comment]
What version of tesseract you try to build?

**Comment by billydekid** [comment]
3.05.00dev
download the zip from github

**Comment by zdenop** [comment]
did you run ./autogen.sh as stated in https://github.com/tesseract-ocr/tesseract/blob/master/INSTALL.GIT.md?

**Comment by billydekid** [comment]
Oops forgot to mention. I run it and looks OK.

`# ./autogen.sh
Running aclocal
Running libtoolize
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `config'.
libtoolize: copying file `config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
Running autoheader
Running automake --add-missing --copy
configure.ac:321: installing 'config/compile'
configure.ac:86: installing 'config/config.guess'
configure.ac:86: installing 'config/config.sub'
configure.ac:69: installing 'config/install-sh'
configure.ac:69: installing 'config/missing'
api/Makefile.am: installing 'config/depcomp'
Running autoconf

All done.
To build the software now, do something like:

$ ./configure [--enable-debug] [...other options]
`

**Comment by billydekid** [comment]
Hmmm... What the right solution on this? Thanks

**Comment by Shreeshrii** [comment]
Try

./autogen.sh
autoreconf -ivf
./configure

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

On Wed, Aug 31, 2016 at 5:28 PM, Bayu Widyasanyata <notifications@github.com

**Comment by amitdo** [comment]
@billydekid
What's the output of `dpkg -l | grep pkg-config` ?

**Comment by zdenop** [comment]
@billydekid : I am sorry I misunderstood your comment - I thought it is fixed.

**Comment by billydekid** [comment]
@Shreeshrii it works! thanks bro! :+1:  taken from **autoreconf** man page
`By default, it only remakes those files that are older than their sources.`

@amitdo here's the output:
```
# dpkg -l | grep pkg-config
ii  pkg-config                            0.26-1ubuntu4                       amd64        manage compile and link flags for libraries
```
Should this "autoreconf -ivf" add to wiki?
Thanks!

**Comment by billydekid** [comment]
Just add some notes. The problem still exist until we should also install the pango lib dev (apt-get install libcogl-pango-dev). I thought it confuses as described on Wiki (https://github.com/tesseract-ocr/tesseract/wiki/Compiling), while it's not necessary to install (lib pango dev) if we're not plan to install training tools.

**Comment by zdenop** [comment]
@billydekid: Does it mean that have to install pango-dev to fix problem? If yes, that it is bug that need to be fixed! (in this case please reopen this issue)

**Comment by billydekid** [comment]
Just add some notes. The problem still exist until we should also install the pango lib dev (apt-get install libcogl-pango-dev). I thought it confuses as described on Wiki (https://github.com/tesseract-ocr/tesseract/wiki/Compiling), while it's not necessary to install (lib pango dev) if we're not plan to install training tools.

**Comment by billydekid** [comment]
That was happened to one of my server. To ensure I will reinstall from fresh on my new vm box, and update / or reopen this issue if it problems.

**Comment by amitdo** [comment]
`libcogl-pango-dev` is not needed by Tesseract!

`libcogl-pango-dev` has these dependencies:

```
libpango1.0-dev
libcairo2-dev
pkg-config (recommended)


```

**Comment by billydekid** [comment]
Hi, Just want to update if it was fine when I installed without pango lib-dev packages (no training tools). Just got WARN messages on config.log. Thanks!
